### PR TITLE
Updated with the latest OL

### PR DESCRIPTION
**Pull request by gkertaseferi**

### CODE REVIEW

**Comment by evelinec** [comment]
@Kubik42 Can you review this PR? Thanks.

**Comment by evelinec** [comment]
@JunyiSun Can you take a look as well? Thanks

**Comment by yeekangc** [comment]
@gkertaseferi, can you please summarize the background for this change?  What's the root cause of the problem here?

Thank you.

**Comment by gkertaseferi** [comment]
The frequency that ConfigSources are consulted and any values are refreshed is controlled by the microprofile.config.refresh.rate Java system property. The units that are used are milliseconds and the default value is 500 meaning that, by default, ConfigSources provides values feed into any Configuration they contribute to, in around half a second. That's why I added a Thread.sleep(600); a bit more than 500 milliseconds because you need to overwrite the file and then wait that minimum amount to make sure the Config code has re-read the file. As per the other changes I just deleted the map because it was reading the same file from the map(which wasn't updating) and now it get's the updated file every time.

**Comment by JunyiSun** [comment]
@gkertaseferi Thank you for investigating on this issue! 

@evelinec I have reviewed the change and it can be merged.

**Comment by yeekangc** [comment]
I want to understand the why before we merge.  @gkertaseferi @junyisun, can you please explain the issue?

**Comment by JunyiSun** [comment]
@yeekangc @gkertaseferi
Did the ConfigSource get consulted instantly in OL version 17.0.0.3? I am curious why the update can be picked up instantly without waiting for more than half second in the earlier version of OL.

**Comment by yeekangc** [comment]
Yes, good point, @JunyiSun.  Missed that.  Can you please get with @gkertaseferi @GraceJansen to understand that?  That is the important and critical point.

**Comment by Kubik42** [comment]
Just tested these changes in FT with 17.0.0.4 and 18.0.0.1 and everything passes. I'm also wondering what changed between 17.0.0.3 and newer versions @yeekangc

**Comment by JunyiSun** [comment]
@Kubik42 changed LATEST to RELEASE

**Comment by JunyiSun** [comment]
I asked Grace, since Gkerta is on vacation, and she said she talked to Tom Evans about it and he didn't think it should have worked at all and doesn't understand why it did with 17003. Indeed we are unable to know what changed between 17003 and the newer version of OL. Anyway, we will investigate more on that , and I think we can merge this PR first since it did solve the issue in a correct way.

**Pull request merged**
